### ISSUE TITLE
Colours aren't being extract from the provided file

### ISSUE THREAD

**Issue by lachlangrose** [Loop3D/map2loop-2#46]
Colours don't seem to be included in the all_sorts file, can you fix this? Need it for LoopStructural paper.

**Comment by yohanderose** [comment]
Colours are now consistent with clut (if in au/polygons exist), or generated and stored within the project.config object as a dictionary and also written out to all_sorts_clean.csv. 4d00f45b1a055f34b6267c551c5c5df1b956a3a4

**Comment by markjessell** [comment]
1) The cmap HAS to be set now, having it set to ='' crashes because we then don't call tidy_data line 755 config.py, we need to be able to NOT use a cmap as well.

2) forcing tidy_data still crashes as the old code that created random colours is gone. Old code:

    ```
if(clut_path  == ''):
       asc = pd.read_csv(tmp_path+'all_sorts_clean.csv',",")
       colours = []
       for i in range(len(asc)):
           r = random.randint(1,256)-1
           g = random.randint(1,256)-1
           b = random.randint(1,256)-1
           hex_rgb = m2l_utils.intstohex((r,g,b))
           colours.append(hex_rgb)
       asc['colour']  =  colours
       asc.to_csv(tmp_path+'all_sorts_clean.csv', index  =  None, header = True)
```

3) The code in save_cmap is based on **all_sorts.csv** when it should be **all_sorts_clean.csv** as it happens after the post-processing that call tidy_data in project.py . See line 609 of config.py

**Comment by yohanderose** [comment]
Hey, thanks for the clear issue 

1. (and 2) Since 789c23acd5d09d0e174e1977d61a6a011b22a7ad, m2l will try to read the provided colour CSV. If it can't do this (issue reading the file/user specified empty path), we randomly generate some colours and create a cmap in config.py::preprocess() (line ~190) that is consistent through the program. You can find this colour info in _all_sorts_clean.csv_ or in the project.config.colour_dict - a dictionary of unit names mapped to the colours they have on the map to be the same in the models.

3.  I have changed save_cmap to read in all_sorts_clean instead of all_sorts, removed the redundant code, and made sure each unit gets the right colour. We still add the _erode_ field in m2l_geometry.py::tidy_data() but append the colour dictionary field in save_cmap(). These fixes pass my tests, but let me know if they work for you. 

![image](https://user-images.githubusercontent.com/38681260/110470400-abca0b80-813f-11eb-97b7-6da795316cb7.png)

**Comment by lachlangrose** [comment]
This still does not work. 

~/map2loop-2/map2loop/config.py in save_cmap(self)
    605 
    606         colours = []
--> 607         for code in all_sorts[self.c_l['u']]:
    608             colours.append([self.colour_dict[code]])
    609 

KeyError MAINUNIT, which is in the c_l file for SA. Should it be using the column name in all_sorts not the column in the input dataset?

**Comment by lachlangrose** [comment]
It works on WA data, can you test on SA data please

**Comment by yohanderose** [comment]
All tests passing in SA for both remote and local sources, with expected/consistent colours c71cadf02bc761c95017f56897aff76448ea53ca

**Comment by yohanderose** [comment]
FYI: You can specify a custom colour scheme for polygons in your maps in a file that resembles this https://gist.githubusercontent.com/yohanderose/c7927fa6f9a2b9e983eeec6941ad9f56/raw/253b33afee74fcb1d487ef1c12093134f31093f4/SA_clut.csv, i.e. setting unit names in your shapefiles and the corresponding hex colours you would like to see.

Then use your custom colour file (even with Loop's sources) using the clut_path param as shown below 
```python
proj = Project(loopdata_state="SA")

proj.update_config(out_dir='sa-remote-customcolours',
                   overwrite="true",
                   bbox_3d={
                                  'minx': 250805.1529856466,
                                  'miny': 6405084.328058686,
                                  'maxx': 336682.921539395,
                                  'maxy': 6458336.085975628,
                                  'base': -3200,
                                  'top': 1200
                              },
                   proj_crs={'init': 'EPSG:28354'},
                   drift_prefix=['T', 'Q', 'water', 'void'],
                   quiet='no-figures',
                   clut_path='SA/data/my_custom_colours.csv')
```
